import "./globals.css"
import { Inter } from "next/font/google"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex min-h-screen flex-col bg-[url(/wood-bg.jpeg)]">
                    {children}
                </main>
            </body>
        </html>
    )
}
